version: 0.2
artifacts:
  files:
    - '**/*'
phases:
 install:
   commands:
     - npm install
 pre_build:
   commands:
     - npm run test
 build:
   commands:
     - echo "build step"
 post_build:
   commands:
     - echo "post_build step"